name: llana-portal

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "55262:55262"
        environment:
            DOMAIN: ${DOMAIN}
            ADMIN_EMAIL: ${ADMIN_EMAIL}

    # docker-app:
    #     container_name: docker-app
    #     image: juicyllama/llana-portal:latest
    #     ports:
    #         - "55262:55262"
    #     environment:
    #         DOMAIN: ${DOMAIN}
    #         ADMIN_EMAIL: ${ADMIN_EMAIL}